version: "18"

services:
  db:
    image: postgres:17.2-alpine
    restart: always
    container_name: "ms-postgres-db"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - "9001:5432"
networks:
  ms-network:
    external: true
